-- MIDI Control Center: model -> ReaLearn Luau preset text.
-- The output is `local MODEL = <literal>` followed by interpreter.luau verbatim, so the preset needs no
-- require() and ReaLearn, the editor and the offline tests all execute the same interpreter.

local G = {}

local function this_dir()
    local src = debug.getinfo(1, "S").source:sub(2)
    return src:match("^(.*)[/\\]") or "."
end
G.DIR = this_dir()

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local s = f:read("*a"); f:close()
    return s
end

function G.interpreter()
    local s = read_file(G.DIR .. "/interpreter.luau")
    if not s then error("interpreter.luau not found next to generator.lua") end
    return s
end

-- Luau literal for a model value. Arrays as { a, b }, objects with sorted keys; strings quoted with %q.
local function literal(v, indent, out)
    local t = type(v)
    if t == "table" then
        local n = 0
        for k in pairs(v) do
            if type(k) ~= "number" or k < 1 or math.floor(k) ~= k then n = -1; break end
            n = n + 1
        end
        local is_array = n >= 0
        if is_array then for i = 1, n do if v[i] == nil then is_array = false end end end
        local pad = string.rep("    ", indent + 1)
        if is_array then
            if n == 0 then out[#out + 1] = "{}"; return end
            out[#out + 1] = "{\n"
            for i = 1, n do
                out[#out + 1] = pad
                literal(v[i], indent + 1, out)
                out[#out + 1] = ",\n"
            end
            out[#out + 1] = string.rep("    ", indent) .. "}"
        else
            local keys = {}
            for k in pairs(v) do keys[#keys + 1] = k end
            table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
            out[#out + 1] = "{\n"
            for _, k in ipairs(keys) do
                local key
                if type(k) == "string" and k:match("^[%a_][%w_]*$") then key = k
                else key = "[" .. string.format("%q", k) .. "]" end
                out[#out + 1] = pad .. key .. " = "
                literal(v[k], indent + 1, out)
                out[#out + 1] = ",\n"
            end
            out[#out + 1] = string.rep("    ", indent) .. "}"
        end
    elseif t == "string" then out[#out + 1] = string.format("%q", v)
    elseif t == "number" then
        if math.floor(v) == v then out[#out + 1] = string.format("%d", v) else out[#out + 1] = string.format("%.14g", v) end
    elseif t == "boolean" then out[#out + 1] = tostring(v)
    else error("cannot serialise " .. t) end
end

function G.model_literal(model)
    local out = {}
    literal(model, 0, out)
    return table.concat(out)
end

function G.header(model, opts)
    opts = opts or {}
    local layouts = {}
    for _, l in ipairs(model.layouts or {}) do layouts[#layouts + 1] = l.name or l.id end
    return "--- name: " .. (opts.name or "Oxygen Pro 61 - Live mode (editor)") .. "\n"
        .. "--- realearn_version: 2.18.0\n"
        .. "--- author: " .. (opts.author or "MIDI Control Center") .. "\n"
        .. "--- description: |\n"
        .. "---     GENERATED by the MIDI Control Center (Scripts/MIDI Control Center/MIDI Control Center.lua) on " .. (opts.date or os.date("%Y-%m-%d %H:%M")) .. ".\n"
        .. "---     Do not edit by hand: change the model in the editor and apply again.\n"
        .. "---     Layouts: " .. table.concat(layouts, " / ") .. ". Banks: " .. #(model.banks or {}) .. ".\n"
        .. "---     Input MIDIIN3 (Oxygen Pro 61) control-only, output MIDIOUT3 (Oxygen Pro 61); needs the Live watcher for sysex, sweeps and tap tempo.\n"
        .. "\n--!strict\n\n"
end

function G.exquis_interpreter()
    local s = read_file(G.DIR .. "/exquis_interpreter.luau")
    if not s then error("exquis_interpreter.luau not found next to generator.lua") end
    return s
end

-- the Exquis unit's preset from model.exquis (nil when the Exquis section is absent or disabled)
function G.generate_exquis(model, opts)
    local x = model.exquis
    if type(x) ~= "table" or not x.enabled then return nil end
    opts = opts or {}
    local head = "--- name: Exquis - REAPER control (editor)\n"
        .. "--- realearn_version: 2.18.0\n"
        .. "--- author: " .. (opts.author or "MIDI Control Center") .. "\n"
        .. "--- description: |\n"
        .. "---     GENERATED by the MIDI Control Center on " .. (opts.date or os.date("%Y-%m-%d %H:%M")) .. ". Do not edit by hand.\n"
        .. "---     Exquis in Developer Mode (mask 2E, pads stay MPE); unit input and output = Exquis. See docs/EXQUIS.md.\n"
        .. "\n--!strict\n\n"
    local model_mod = require("model")
    model_mod.exquis_migrate(x)
    local xm = {}
    for k, v in pairs(x) do xm[k] = v end
    xm.port1_input_device = model.port1_input_device or xm.port1_input_device
    -- a captured layout snapshot (see "Exquis - Capture layout snapshot.lua") is embedded when the file exists
    local snap = read_file(G.DIR .. "/exquis_snapshot.txt")
    if snap then
        local hex = {}
        for line in snap:gmatch("[^\r\n]+") do
            if line:sub(1, 1) ~= "#" then for h in line:gmatch("%x%x") do hex[#hex + 1] = h end end
        end
        if #hex > 0 then xm.snapshot = table.concat(hex, " ") end
    end
    return head .. "local MODEL = " .. G.model_literal(xm) .. "\n\n" .. G.exquis_interpreter()
end

function G.generate(model, opts)
    return G.header(model, opts) .. "local MODEL = " .. G.model_literal(model) .. "\n\n" .. G.interpreter()
end

-- Run the generated text (or a model) through a Lua interpreter and return the preset table; for tests/self-checks.
function G.evaluate(text)
    local chunk, err = load(text, "generated preset", "t")
    if not chunk then return nil, err end
    local ok, res = pcall(chunk)
    if not ok then return nil, tostring(res) end
    return res
end

return G
